version: '3.8'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/
            - ./docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
        ports :
            - "8080:80"
        container_name: project_nginx
        depends_on:
            - app
    app:
        build:
            context: docker/app
            dockerfile: Dockerfile
        volumes:
            - ./backend/:/var/www/backend
        container_name: project_app
        depends_on:
            - db
    db:
        build:
            context: docker/db
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: blog_database
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "12345:3306"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: project_db
    frontend:
        build:
            context: frontend
            dockerfile: Dockerfile
        expose:
            - 5173
        restart: always
        volumes:
            - ./frontend:/var/www/frontend
        ports:
            - "5137:5138"
        container_name: project_frontend